module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#191c1e",
        "on-tertiary-container": "#818486",
        "on-error-container": "#93000a",
        "on-surface": "#0b1c30",
        "primary-container": "#131b2e",
        "on-secondary-fixed-variant": "#004395",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#e0e3e5",
        "secondary-container": "#2170e4",
        "on-primary-fixed": "#131b2e",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "on-tertiary-fixed": "#191c1e",
        "secondary-fixed": "#d8e2ff",
        "surface-container-high": "#dce9ff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#213145",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed": "#001a42",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-primary": "#ffffff",
        "secondary": "#0058be",
        "inverse-on-surface": "#eaf1ff",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-low": "#eff4ff",
        "surface-variant": "#d3e4fe",
        "primary-fixed": "#dae2fd",
        "surface-tint": "#565e74",
        "on-surface-variant": "#45464d",
        "tertiary": "#000000",
        "surface-container": "#e5eeff",
        "inverse-primary": "#bec6e0",
        "primary": "#0f172a",
        "on-secondary-container": "#fefcff",
        "outline": "#76777d",
        "on-tertiary-fixed-variant": "#444749",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#7c839b",
        "surface-container-highest": "#d3e4fe",
        "surface": "#f8f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "base": "8px",
        "stack-sm": "12px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-lg": "48px",
        "container-max": "1280px",
        "stack-xs": "4px",
        "stack-md": "24px",
        "stack-xl": "80px"
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
      }
    },
  },
  plugins: [],
}
